# Implentations, Applications, and Tools

In [1]:
% pip install numpy # A library with functions to operate on n- dimensional arrays and matrices.
% pip install scikit-learn #  A highly advanced module for machine learning. It contains a good number of algorithms for classification, regressio, clustering etc.
% pip install matplotlib # This a plotting library that makes use of NumPy to graph a good variety of charts
% pip install pandas # The library that deals with data manipulation
% pip install textblob # read data from cloud, from blobs

UsageError: Line magic function `%` not found.


# Data preprocessing

## Why to process raw data?

raw data = json files, txt, pdfs, word document etc., tables etc.
1. structured data, unstructured data, semi-structured?
2. feature selection, evaluate the features
3. historical data, enough features
4. ### Missing Data
- remove missing rows
- fill with the median, the max, the minumum the missing rows per column


In [6]:
import numpy as np
import pandas as pd
data = pd.DataFrame([
    [4.,45.,984.],
    [np.NAN, np.NAN, 5.],
    [94., 23., 55.],
])
data # to print the DataFrame

0     1      2
0   4.0  45.0  984.0
1   NaN   NaN    5.0
2  94.0  23.0   55.0

In [7]:
print(data.fillna(2.5))

      0     1      2
0   4.0  45.0  984.0
1   2.5   2.5    5.0
2  94.0  23.0   55.0


In [8]:
print(data.fillna(data.mean()))

      0     1      2
0   4.0  45.0  984.0
1  49.0  34.0    5.0
2  94.0  23.0   55.0


In [10]:
print(data.fillna(data.max()))

      0     1      2
0   4.0  45.0  984.0
1  94.0  45.0    5.0
2  94.0  23.0   55.0


In [11]:
print(data.fillna(data.min()))

      0     1      2
0   4.0  45.0  984.0
1   4.0  23.0    5.0
2  94.0  23.0   55.0


# Feature scaling 



In [12]:
data = pd.DataFrame([
    [58.,1.,43.],
    [10., 200., 65.],
    [20., 75., 7.],
])
data # to print the DataFrame

0      1     2
0  58.0    1.0  43.0
1  10.0  200.0  65.0
2  20.0   75.0   7.0

# Min-Max scalar

stand_scalar = preprocessing.StandardScaler().fit(data)
results = stand_scalar.transform(data)
print(results)

In [19]:
# first to install the library

%pip install scikit-learn



Note: you may need to restart the kernel to use updated packages.


In [21]:
from sklearn import preprocessing

data = pd.DataFrame([
    [58.,1.,43.],
    [10., 200., 65.],
    [20., 75., 7.],
])

scaled_values = preprocessing.MinMaxScaler(feature_range = (0,1))
results = scaled_values.fit(data).transform(data)
print(results)

[[1.         0.         0.62068966]
 [0.         1.         1.        ]
 [0.20833333 0.3718593  0.        ]]


# Standard scalar 
## gaussian distribution

In [22]:
from sklearn import preprocessing

data = pd.DataFrame([
    [58.,1.,43.],
    [10., 200., 65.],
    [20., 75., 7.],
])

stand_scalar = preprocessing.StandardScaler().fit(data)
results = stand_scalar.transform(data)
print(results)

[[ 1.38637564 -1.10805456  0.19519899]
 [-0.93499753  1.31505377  1.11542277]
 [-0.45137812 -0.2069992  -1.31062176]]


# Binarizing data



In [4]:
from sklearn import preprocessing
import pandas as pd
data = pd.DataFrame([
    [58,1,43],
    [10, 200, 65],
    [20, 75, 7],
])

binary_scalar = preprocessing.Binarizer(threshold=50).fit(data)
results =binary_scalar.transform(data)
print(results)

[[1 0 0]
 [0 1 1]
 [0 1 0]]


# Machine Learning 

## three categories 
1. Supervised learning: an algorith is fed a set of inputs and their corresponding outputs. The algorithm then has to figure out what the output will be for an unfamiliar input.
2. Unsupervised learning: without the relationship that exists between a set of inputs and output variables.
3. Reinforcement learning: the computer in this kind of learning dynamically interacts with the environemt in such way as to imporve its performance. 

In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
X= iris.data # depending on lenght and width to predict the flower
y= iris.data # 
#print(X)
#print(y)

#split data

#how to apply RandomForestClassifier

#how to measure the accuracy of the classifier




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.